In [1]:
import pandas as pd
from pprint import pprint

INPUT_FILE = 'downloads/microdados_enem_2024/DADOS/RESULTADOS_2024_CE.csv'

df = pd.read_csv(INPUT_FILE)
pprint(df.columns)
df.head()

Index(['NU_SEQUENCIAL', 'NU_ANO', 'CO_ESCOLA', 'CO_MUNICIPIO_ESC',
       'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC', 'TP_DEPENDENCIA_ADM_ESC',
       'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC', 'CO_MUNICIPIO_PROVA',
       'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA', 'SG_UF_PROVA', 'TP_PRESENCA_CN',
       'TP_PRESENCA_CH', 'TP_PRESENCA_LC', 'TP_PRESENCA_MT', 'CO_PROVA_CN',
       'CO_PROVA_CH', 'CO_PROVA_LC', 'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH',
       'NU_NOTA_LC', 'NU_NOTA_MT', 'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH',
       'TX_RESPOSTAS_LC', 'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN',
       'TX_GABARITO_CH', 'TX_GABARITO_LC', 'TX_GABARITO_MT',
       'TP_STATUS_REDACAO', 'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3',
       'NU_NOTA_COMP4', 'NU_NOTA_COMP5', 'NU_NOTA_REDACAO'],
      dtype='object')

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,2262755,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,500706,2024,23007648.0,2307809.0,Marco,23.0,CE,2.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,160.0,200.0,160.0,880.0
3,1847098,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,140.0,200.0,160.0,140.0,160.0,800.0
4,2023802,2024,23277971.0,2302701.0,Campos Sales,23.0,CE,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df.head().transpose()

,0,1,2,3,4
NU_SEQUENCIAL,206403,2262755,500706,1847098,2023802
NU_ANO,2024,2024,2024,2024,2024
CO_ESCOLA,23052929.0,NaN,23007648.0,NaN,23277971.0
CO_MUNICIPIO_ESC,2301406.0,NaN,2307809.0,NaN,2302701.0
NO_MUNICIPIO_ESC,Aratuba,NaN,Marco,NaN,Campos Sales
CO_UF_ESC,23.0,NaN,23.0,NaN,23.0
SG_UF_ESC,CE,NaN,CE,NaN,CE
TP_DEPENDENCIA_ADM_ESC,2.0,NaN,2.0,NaN,2.0
TP_LOCALIZACAO_ESC,1.0,NaN,1.0,NaN,2.0
TP_SIT_FUNC_ESC,1.0,NaN,1.0,NaN,1.0
CO_MUNICIPIO_PROVA,2301406,2304400,2307809,2302503,2302701
NO_MUNICIPIO_PROVA,Aratuba,Fortaleza,Marco,Brejo Santo,Campos Sales
CO_UF_PROVA,23,23,23,23,23
SG_UF_PROVA,CE,CE,CE,CE,CE
TP_PRESENCA_CN,1,0,1,1,0
TP_PRESENCA_CH,1,0,1,1,0
TP_PRESENCA_LC,1,0,1,1,0
TP_PRESENCA_MT,1,0,1,1,0
CO_PROVA_CN,1420.0,NaN,1422.0,1422.0,NaN
CO_PROVA_CH,1383.0,NaN,1384.0,1384.0,NaN
CO_PROVA_LC,1395.0,NaN,1396.0,1396.0,NaN
CO_PROVA_MT,1408.0,NaN,1410.0,1410.0,NaN
NU_NOTA_CN,436.8,NaN,497.4,630.4,NaN
NU_NOTA_CH,377.8,NaN,483.3,658.4,NaN
NU_NOTA_LC,423.4,NaN,535.2,619.9,NaN
NU_NOTA_MT,427.1,NaN,514.9,495.0,NaN
TX_RESPOSTAS_CN,CAABADDBBBACACACDEABDBABDDCCBACDCCBAACCABCBAC,NaN,ACBEDACBEDACBEDACBEDACBEDACBEDACBEDACBEDACBED,BDEEDABAEBBEADDDBEEEDCBCABBDEDEBBBCBCEBDCBBCA,NaN
TX_RESPOSTAS_CH,BEABBCDABCDBAEEBDDABCCDAADDABACDDAB..........,NaN,EEDEEDABAABDEADBECEACBAABCEAEBAEEACBBCAAECBEA,AADABCDBECEDEDBBEBEDBADECBEADDEEEACBAEBAECEDA,NaN
TX_RESPOSTAS_LC,BCADBCDCEDBDDBDDCDBCBB*BBDEAEEBCDCABBDDAAECEE,NaN,DCEDCDADECBBDAECADDABDEEEDBDCDBDEBAADDEECCBCA,AACEBDADECBBDBEEBDCDACAEDDCADBBDEBDCBDBECCBBC,NaN
TX_RESPOSTAS_MT,CBDCCADBBECCBADEACCBDCACECDDABBDBADBAAEDBCCAB,NaN,ACBEDACEEDACBEDACBEDACBEDACBEDACBEDACBEDACBED,BBCCCAACBBCBDBBACBBBBCBCCBCCBCEAEEACCABBBCCEC,NaN
TP_LINGUA,1,1,1,0,1
TX_GABARITO_CN,CAEDAACCAEEXCBBAEDBBCAACDEDCBCEECAAEDDDEBBDDB,NaN,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,BBCEDBBAEXCCAEDDBCAEDAACAAEDDDEBBECBCEEDCAACD,NaN
TX_GABARITO_CH,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,NaN,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,NaN
TX_GABARITO_LC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,NaN,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,NaN
TX_GABARITO_MT,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,NaN,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,NaN
TP_STATUS_REDACAO,1.0,NaN,1.0,1.0,NaN
NU_NOTA_COMP1,80.0,NaN,160.0,140.0,NaN
NU_NOTA_COMP2,60.0,NaN,200.0,200.0,NaN
NU_NOTA_COMP3,60.0,NaN,160.0,160.0,NaN
NU_NOTA_COMP4,80.0,NaN,200.0,140.0,NaN
NU_NOTA_COMP5,20.0,NaN,160.0,160.0,NaN
NU_NOTA_REDACAO,300.0,NaN,880.0,800.0,NaN